import mongoose from 'mongoose';

const mockInterviewSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    resumeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Resume',
      // Required agar mock interview strictly ek resume base par hua ho
    },
    confidenceScore: {
      type: Number,
      min: 0,
      max: 100,
      required: true,
      description: "Overall confidence score evaluated by AI during the session"
    },
    technicalScore: {
      type: Number,
      min: 0,
      max: 100,
      required: true,
      description: "Technical accuracy score evaluated by AI"
    },
    aiFeedback: {
      type: String,
      required: true,
      description: "Detailed feedback generated by AI"
    },
    duration: {
      type: Number, // Duration in minutes (e.g., 10 or 15 mins)
      required: true,
    },
    date: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true, // Automatically adds 'createdAt' and 'updatedAt' fields
  }
);

const MockInterview = mongoose.model('MockInterview', mockInterviewSchema);

export default MockInterview;
